<?php

namespace App\Services;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\File;

class PlatformOption
{
    // protected Collection $collection;

    public function __construct()
    {
        // $filepath = base_path('resources/data/platform/option-values.json');
        // $this->collection = collect(json_decode(File::get($filepath), true));
    }

    /**
     * Get an item from the collection by key.
     */
    // public function get($key, $default = null)
    // {
    //     return $this->collection->get($key, $default);
    // }

    public static function auction_type(): array
    {
        return [
            "Antique Furniture",
            "Antique Religious Decor",
            "Art Nouveau & Art Deco Furniture",
            "Automobilia",
            "Automobilia Art & Posters",
            "Automobilia Car Parts",
            "Automobilia Literature",
            "Automobilia Signs & Lightboxes",
            "Aviation",
            "Boho Chic",
            "Bonsai Trees",
            "Breitling Watches",
            "Cartier Watches",
            "Christmas Decor",
            "Classic Home Decor",
            "Clocks",
            "Comic Figurines & Merchandise",
            "Comics (Private Collection)",
            "Comics (Risqué)",
            "Comics in Dutch",
            "Comics in French",
            "Comics in Italian",
            "Contemporary Design",
            "Decorative Salvage",
            "Designer Furniture",
            "Disney Animation",
            "Disney Comic Art",
            "Disney Figures & Merchandise",
            "English Country House",
            "Exclusive Antiques",
            "Exclusive Art Nouveau & Art Deco",
            "Exclusive Automobilia",
            "Exclusive Design",
            "Exclusive Watches",
            "Ferrari Automobilia",
            "French Elegance",
            "Garden Furniture & Decorations",
            "Hergé / Tintin Comic Books",
            "Hergé / Tintin Figures & Merchandise",
            "Hollywood Glamour",
            "Home Inspiration & Trends",
            "IWC Watches",
            "Industrial Design",
            "International Comics",
            "Japanese Figurines & Merchandise",
            "Longines Watches",
            "Mediterranean House",
            "Modern Home Decor",
            "Motobilia",
            "New Seller Watches",
            "Omega Watches",
            "Pocket Watches",
            "Porsche Automobilia",
            "Premium Watches",
            "Religious Decor",
            "Rolex Watches",
            "Seiko Watches",
            "TAG Heuer Watches",
            "Tudor Watches",
            "US Comics",
            "Unused Watches",
            "Vintage Furniture",
            "Vintage Watches",
            "Watch Accessories",
            "Zenith Watches"
        ];
    }

    public static function object_types(): array
    {
        return [
            "Automaton pocket watch",
            "Chronograph pocket watch",
            "Chronograph watch",
            "Digital watch",
            "Erotic pocket watch",
            "Marriage watch",
            "Mechanical watch",
            "Pocket watch",
            "Smart watch",
            "Stopwatch",
            "Watch"
        ];
    }

    public static function external_reference_colour(): array
    {
        return [
            "Gray",
            "Blue",
            "Green",
            "Orange",
            "Red"
        ];
    }

    public static function language(): array
    {
        return [
            "English",
            "Dutch",
            "French",
            "German",
            "Italian",
            "Spanish",
            "Portuguese",
            "Polish"
        ];
    }

    public static function shipping_country_name(): array
    {
        return [
            "Austria",
            "Belgium",
            "Bulgaria",
            "Switzerland",
            "Czech Republic",
            "Germany",
            "Denmark",
            "Estonia",
            "Spain",
            "Finland",
            "France",
            "Greece",
            "Croatia",
            "Hungary",
            "Ireland",
            "Iceland",
            "Italy",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Latvia",
            "Monaco",
            "Malta",
            "The Netherlands",
            "Norway",
            "Poland",
            "Portugal",
            "Romania",
            "Sweden",
            "Slovenia",
            "Slovak Republic",
            "San Marino",
            "Cyprus",
            "Canary Islands",
            "United Kingdom",
            "United States",
            "China",
            "Hong Kong",
            "Israel",
            "Japan",
            "Macao, China",
            "Singapore",
            "Türkiye",
            "Taiwan"
        ];
    }

    public static function shipping_country_code(): array
    {
        return [
            "at",
            "be",
            "bg",
            "ch",
            "cz",
            "de",
            "dk",
            "ee",
            "es",
            "fi",
            "fr",
            "gr",
            "hr",
            "hu",
            "ie",
            "is",
            "it",
            "li",
            "lt",
            "lu",
            "lv",
            "mc",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "se",
            "si",
            "sk",
            "sm",
            "cy",
            "ic",
            "gb",
            "us",
            "cn",
            "hk",
            "il",
            "jp",
            "mo",
            "sg",
            "tr",
            "tw"
        ];
    }

    public static function d_brand(): array
    {
        return [
            "5.11 Tactical",
            "88 Rue du Rhone",
            "A. Lange & Söhne",
            "A.Mantei",
            "Accurist",
            "Accutron",
            "Aerowatch",
            "Alain Silberstein",
            "Alba",
            "Alfred Dunhill",
            "Alpha Sierra",
            "Alpina",
            "Altanus",
            "Alviero Martini 1a Classe",
            "Ancre",
            "Android",
            "Angelus",
            "Anonimo",
            "Antoine Nicolas 1986",
            "Antoine Preziuso",
            "Apple",
            "Aquanautic",
            "Aquastar",
            "Aquaswiss",
            "Archimede",
            "Arctos",
            "Ardath",
            "Aristo",
            "Armand Nicolet",
            "Armida",
            "Armin Strom",
            "Armitron",
            "Arnold & Son",
            "Aspen Jewelry & Watches",
            "Astronic",
            "Atlantic",
            "Audemars Piguet",
            "Auguste Reymond",
            "Auricoste",
            "Automatic",
            "B.R.M.",
            "BALL",
            "BMW",
            "BWC-Swiss",
            "Badollet",
            "Balmain",
            "Barthelay",
            "Baume & Mercier",
            "Bausele",
            "Bedat & Co.",
            "Bell & Ross",
            "Benrus",
            "Bernhard H. Mayer",
            "Bertolucci",
            "Beuchat",
            "Bifora",
            "Blancpain",
            "Boccia",
            "Boegli",
            "Bombardier",
            "Bomberg",
            "Boucheron",
            "Bovet",
            "Braun",
            "Breguet",
            "Breil",
            "Breitling",
            "Bremont",
            "Bruno Söhnle",
            "Bucherer",
            "Buler",
            "Bulova",
            "Bunz",
            "Burberry",
            "Buren",
            "Bvlgari",
            "CCCP",
            "CT Scuderia",
            "CWC",
            "Cabestan",
            "Cadola",
            "Camy",
            "Candino",
            "Caravelle",
            "Carl F. Bucherer",
            "Cartier",
            "Casio",
            "Catena",
            "Cattin",
            "Cerruti",
            "Certina",
            "Chanel",
            "Charmex",
            "Charriol",
            "Chaumet",
            "Chopard",
            "Christiaan v.d. Klaauw",
            "Christian Bernard",
            "Christian Dior",
            "Christopher Ward",
            "Chromachron",
            "Chronographe Suisse",
            "Chronoswiss",
            "Chronotech",
            "Cimier",
            "Citizen",
            "Claude Bernard",
            "Claude Meylan",
            "Clerc",
            "Clodia",
            "Coinwatch",
            "Concord",
            "Condor",
            "Consul of Switzerland",
            "Cornavin",
            "Cortébert",
            "Corum",
            "Cover",
            "Crepas",
            "Croton",
            "Cuervo y Sobrinos",
            "Cvstos",
            "Cyma",
            "Cyrus Geneve",
            "DWISS",
            "Damasko",
            "Daniel Roth",
            "Darwil",
            "David Yurman",
            "Davosa",
            "De Grisogono",
            "DeLaCour",
            "DeLaneau",
            "DeWitt",
            "Deep Blue",
            "Delbana",
            "Delma",
            "Delvina",
            "Disney",
            "Dodane",
            "Dogma",
            "Dolce & Gabbana",
            "Doxa",
            "Dreyfuss & Co.",
            "DuBois et fils",
            "Dubey & Schaldenbrand",
            "Dugena",
            "Dunhill",
            "Duward",
            "Duxot",
            "Ebel",
            "Eberhard & Co.",
            "Edox",
            "Election",
            "Elgin Watch Company",
            "Endura",
            "Enicar",
            "Enigma",
            "Ennebi",
            "Epos",
            "Ernest Borel",
            "Ernst Benz",
            "Eterna",
            "Eterna-Matic",
            "Fabergé",
            "Favre-Leuba",
            "Fendi",
            "Ferrari",
            "Festina",
            "Fonderia Lab",
            "Forget",
            "Fortis",
            "Franc Vila",
            "Franck Muller",
            "Fromanteel",
            "Frédérique Constant",
            "GUB Glashütte",
            "GaGà Milano",
            "Gallet",
            "Garmin",
            "Georg Jensen",
            "Geovani",
            "Gevril",
            "Gigandet",
            "Gio Monaco",
            "Giorgio Armani",
            "Girard-Perregaux",
            "Glashütte Original",
            "Glycine",
            "Golana",
            "Golftime",
            "Graff",
            "Graham",
            "Greubel Forsey",
            "Grimoldi",
            "Grovana",
            "Gruen",
            "Gucci",
            "Guess",
            "Guy Ellia",
            "Gérald Genta",
            "Gübelin",
            "H.Moser & Cie.",
            "HD3",
            "HTO Watches",
            "HYT",
            "Haemmer",
            "Hager",
            "Hajime Asaoka",
            "Hamilton",
            "Hanhart",
            "Hanowa",
            "Harry Winston",
            "Harwood",
            "Haste",
            "Hautlence",
            "Hebdomas",
            "Helbros",
            "Helvetia",
            "Hentschel",
            "Heritor",
            "Hermès",
            "Heuer",
            "Hirsch",
            "Hislon",
            "Howard",
            "Hublot",
            "Huguenin",
            "Hysek",
            "I.T.A.",
            "IAXA",
            "IWC",
            "Ikepod",
            "Illinois",
            "Ingersoll",
            "Invicta",
            "J. Chevalier",
            "JS Watch co.",
            "Jacob & Co.",
            "Jacob Jensen",
            "Jacques Etoile",
            "Jacques Lemans",
            "Jaeger-LeCoultre",
            "Jaguar",
            "Jaques Richal",
            "Jaquet-Droz",
            "Jean Marcel",
            "Jean Perret",
            "Jean-Pierre Lepine",
            "Jean d'Eve",
            "JeanRichard",
            "Jordi",
            "Jorg Hysek",
            "Jovial",
            "Jowissa",
            "Jules Jürgensen",
            "Junghans",
            "Junkers",
            "Juvenia",
            "Kadloo",
            "Kelek",
            "Kienzle",
            "Korloff",
            "Krieger",
            "L.Leroy",
            "Lacher",
            "Laco",
            "Lamborghini",
            "Lambretta",
            "Lancaster",
            "Lancia",
            "Lanco",
            "Lassale",
            "Le Phare",
            "Leandri",
            "Lemania",
            "Leonard",
            "Leonidas",
            "Levrette",
            "Lip",
            "Locman",
            "Longines",
            "Lorenz",
            "Lotus",
            "Louis Erard",
            "Louis Moinet",
            "Louis Vuitton",
            "Lucerne Salterello",
            "Lucien Piccard",
            "Lucien Rochat",
            "Luminox",
            "MAT",
            "MB&F",
            "MERCURY",
            "MIMO",
            "MWC (Military Watch Co.)",
            "Magellan",
            "Manufacture Royal",
            "Maranello",
            "Marathon",
            "Margi",
            "Martin Braun",
            "Marvin",
            "Mathey-Tissot",
            "Mauboussin",
            "Maurice Lacroix",
            "Maurice de Mauriac",
            "Mazzucato",
            "Meccaniche Veloci",
            "Megisto",
            "Meister Anker",
            "Meistersinger",
            "Memorigin",
            "Memphis Belle",
            "Mercedes-Benz",
            "Mercure",
            "Meyers",
            "Michel Herbelin",
            "Michel Jordi",
            "Michele Watches",
            "Mido",
            "Military European Company",
            "Milleret",
            "Milus",
            "Minerva",
            "Momentus",
            "MomoDesign",
            "Mondaine",
            "Mondia",
            "Monet",
            "Mont d'Or",
            "Montblanc",
            "Montega",
            "Montres de Luxe",
            "Mortima",
            "Movado",
            "MuDu",
            "Mulco",
            "Murex",
            "Mühle Glashütte",
            "N.B. Yäeger",
            "N.O.A.",
            "NauticFish",
            "Nautica",
            "Navitec",
            "Nisus",
            "Nite",
            "Nivada",
            "Nomos",
            "Nubeo",
            "Obris Morgan",
            "Oceaneva",
            "Officina del Tempo",
            "Officine Panerai",
            "Ogival",
            "Ollech & Wajs",
            "Olma",
            "Omax",
            "Omega",
            "Omega x Swatch",
            "Optima",
            "Orator",
            "Orfina",
            "Orient",
            "Oris",
            "Osco",
            "Out of Order",
            "PZero",
            "Panerai",
            "Parmigiani Fleurier",
            "Pasquale Bruni",
            "Patek Philippe",
            "Paul Buhré",
            "Paul Picot",
            "Pequignet",
            "Perigáum",
            "Perrelet",
            "Perseo",
            "Peugeot",
            "Philip Watch",
            "Philipp Plein",
            "Philippe Dufour",
            "Piaget",
            "Picard & Cie",
            "Pierce 1883",
            "Pierre Balmain",
            "Pierre DeRoche",
            "Pierre Kunz",
            "Pierre Lannier",
            "Pilo & Co.",
            "Piquot Meridien",
            "Pirelli",
            "Poljot International",
            "Pomellato",
            "Pontiac",
            "Porsche Design",
            "Potens",
            "Precimax",
            "Prim",
            "Prima Ancre",
            "Prisma",
            "Pronto",
            "Pryngeps",
            "Précibel",
            "Pulsar",
            "Pégoud",
            "Quinting",
            "RSW",
            "Radiant",
            "Rado",
            "Raid Watch",
            "Raidillon",
            "Ralf Tech",
            "Raymond Weil",
            "Rebellion",
            "Reconvilier",
            "Record",
            "Reign",
            "Ressence",
            "Revue Thommen",
            "Rexa",
            "Richard & Co.",
            "Richard Mille",
            "Ritmo Mundo",
            "Roamer",
            "Roberge",
            "Roberto Cavalli",
            "Rodania",
            "Rodolphe",
            "Roeya",
            "Roger Dubuis",
            "Rolex",
            "Romain Jerome",
            "Romanson",
            "Roskopf",
            "Rosskopf",
            "Rotary",
            "Roxy",
            "S.T. Dupont",
            "Saint Honoré",
            "Salvatore Ferragamo",
            "Sandoz",
            "Sarcar",
            "Schaumburg Watch",
            "Schild",
            "Schwarz Etienne",
            "Sea-God",
            "Sector",
            "Seiko",
            "Sevenfriday",
            "Shellman",
            "Shinola",
            "Sicura",
            "Silvana",
            "Sinn",
            "Sinobi",
            "Snyper",
            "Solvil",
            "Sothis",
            "Soyuz",
            "Spazio24",
            "Speake-Marin",
            "Squale",
            "Stadlin",
            "Stauer",
            "Stefano Braga",
            "Steiner Limited",
            "Steinhart",
            "Steinway & Sons",
            "Stowa",
            "Stührling Original",
            "Sultana",
            "Suunto",
            "Swarovski",
            "Swatch",
            "Swiss Army",
            "Swiss Eagle",
            "Swiss Military",
            "Swiza",
            "TAG Heuer",
            "TB Buti",
            "TW Steel",
            "Tavannes",
            "Techno Master",
            "TechnoMarine",
            "Technos",
            "Tecnotempo",
            "Tempvs Compvtare",
            "Terra Cielo Mare",
            "Texas Instruments",
            "Theorein",
            "Tiffany & Co.",
            "Tiret",
            "Tissot",
            "Titan",
            "Titoni",
            "Tom Ford",
            "Tonino Lamborghini",
            "Tool Watch",
            "Torgoen",
            "Tourneau",
            "Traser",
            "Tresor Paris",
            "Tressa",
            "Triumph",
            "Tsovet",
            "Tudor",
            "Tutima",
            "U-Boat",
            "Ublast",
            "Ulysse Nardin",
            "Unbranded",
            "Unikatuhren",
            "Union",
            "Union Glashütte",
            "Universal Genève",
            "Urwerk",
            "Utinam",
            "Vacheron Constantin",
            "Valbray",
            "Van Cleef & Arpels",
            "Van Der Bauwede",
            "Versace",
            "Viceroy",
            "Victorinox",
            "Vidar",
            "Villemont",
            "Vincent Calabrese",
            "Vixa",
            "Vogard",
            "Volkswagen",
            "Vostok",
            "Voutilainen",
            "Vuillemin Regnier",
            "Vulcain",
            "Wakmann",
            "Waldan International",
            "Waltham",
            "Wempe",
            "Wenger",
            "Werenbach",
            "West End Watch Co.",
            "Westar",
            "Wittnauer",
            "Wyler",
            "Wyler Vetta",
            "Yema",
            "Yves Saint Laurent",
            "Zenith",
            "Zeno-Watch Basel",
            "ZentRa",
            "Zeppelin",
            "Zodiac"
        ];
    }

    public static function d_model(): array
    {
        return [
            "21 Chronoscaph",
            1966,
            "2000 Series",
            "Admiral",
            "Admiral's Cup",
            "Aerospace",
            "Aikon Tide",
            "Aion",
            "Air Constellation Automatic",
            "Air-King",
            "Alpine Eagle",
            "Altiplano",
            "Amvox",
            "Aquanaut",
            "Aquaracer",
            "Aquaracer 300M",
            "Aquaracer 500M",
            "Aquaracer Calibre 5",
            "Aquaracer Professional",
            "Aquatimer",
            "Aquis",
            "Arceau",
            "Artelier",
            "Artelier Date Diamonds Automatic",
            "Astron",
            "Audi Sport",
            "Autavia",
            "Automatic \"NobleTime\"",
            "Automatic Super Titanium",
            "Aviator 8",
            "B.Zero1",
            "BR 01",
            "BR 02",
            "BR 03",
            "BR 05",
            "BR V1",
            "BR V2",
            "Baignoire",
            "Ballon Bleu",
            "Bentley",
            "Big Bang",
            "Big Bang King",
            "Big Crown",
            "Big Crown Pointer Date",
            "Big Crown ProPilot",
            "Black Bay",
            "Black Bay 58",
            "Black Bay Gmt",
            "Black Croco",
            "Bubble",
            "CO-1 Chronograph",
            "Calatrava",
            "Calculator",
            "Calibre de Cartier",
            "Calibre de Cartier Diver",
            "Cape Cod",
            "Capeland",
            "Carbongold",
            "Carrera",
            "Carrera Calibre 5",
            "Carrera Calibre 6",
            "Carrera Calibre 16",
            "Carrera Calibre 1887",
            "Carrera Calibre Heuer 01",
            "Carrera Calibre Heuer 02",
            "Carrera Chronograph",
            "Carrera Lady",
            "Casablanca",
            "Cellini",
            "Chemin Des Tourelles Powermatic 80",
            "Chrono-Matic",
            "Chrono Orbs",
            "Chrono Round",
            "Chronofighter",
            "Chronograph 100M \"Chronosphere\"",
            "Chronoliner",
            "Chronomat",
            "Chronomat B01",
            "Chronomat Blackbird",
            "Chronomat Evolution",
            "Chronomat Vitesse",
            "Chronoracer Rattrapante",
            "Cintrée Curvex",
            "Class",
            "Classic Chronograph",
            "Classic Date Automatic",
            "Classic Fusion",
            "Classics",
            "Classics Art Deco",
            "Classics Carrée",
            "Classics Delight",
            "Classics GMT",
            "Classics Heart Beat",
            "Classics Index",
            "Classics Index Automatic",
            "Classics Lady",
            "Classics Moonphase",
            "Classima",
            "Classique",
            "Clifton",
            "Clifton Club",
            "Clipper",
            "Clé",
            "Cockpit",
            "Code 11.59",
            "Colt",
            "Colt Chronograph",
            "Colt GMT",
            "Colt Lady",
            "Colt Military",
            "Colt Oceane",
            "Connected",
            "Conquest",
            "Conquistador",
            "Constellation",
            "Constellation Automatic",
            "Constellation Co-Axial",
            "Constellation Double Eagle",
            "Constellation F300Hz",
            "Constellation Manhattan",
            "Constellation Master Chronometer",
            "Constellation Megaquartz",
            "Constellation Mini",
            "Constellation Pie Pan",
            "Constellation Quadra",
            "Contessa Lady",
            "Cosmograph Daytona",
            "Cosmograph Daytona Zenith",
            "Coutura",
            "Crosswind",
            "Da Vinci",
            "Datejust",
            "Datejust II",
            "Datejust Lady",
            "Datejust Oysterquartz",
            "Datejust Turn-O-Graph",
            "Day-Date",
            "Daytona",
            "De Ville",
            "De Ville Automatic",
            "De Ville Chronoscope",
            "De Ville Classic",
            "De Ville Co-Axial",
            "De Ville Hour Vision",
            "De Ville Prestige",
            "De Ville Trésor",
            "Defy",
            "Defy Skyline",
            "Defy Xtreme",
            "Delfin Chronograph",
            "Diagono",
            "Diver 1000M \"Ocean Force\"",
            "Divers Sixty-Five",
            "Divers Sixty-Five Automatic",
            "Divers Sixty-Five Cotton Candy Bronze Automatic",
            "Dolcevita",
            "Drive",
            "Dynamic",
            "Dynamic Helix",
            "Dynamic Solar System",
            "El Primero",
            "El Primero Chronomaster",
            "Elegant",
            "Eliros",
            "Elite",
            "Ellipse",
            "Endurance Pro",
            "Eternity Gent Slim Line",
            "Eternity Lady",
            "Evidenza",
            "Explorer",
            "Explorer II",
            "Ferrari",
            "Fifty Fathoms",
            "Flagship",
            "Formula 1",
            "Formula 1 Big Date",
            "Formula 1 Chronograph",
            "Freedom",
            "GMT-Master",
            "GMT-Master II",
            "GMT-Master II Batman",
            "GMT-Master II Coke",
            "GMT-Master II Pepsi",
            "GMT-Master Pepsi",
            "GST",
            "Galactic",
            "Galaxis",
            "Genève",
            "Genève Dynamic",
            "Genève Electronic",
            "Glamour",
            "Globemaster",
            "Globetrotter",
            "Gondolo",
            "Grand Carrera",
            "Grand Prix de Monaco Historique",
            "Grand Seiko",
            "Grandevitesse",
            "Hampton",
            "Happy Diamonds",
            "Happy Sport",
            "Harpoon Raider Automatic 500M",
            "Heritage",
            "Heritage Chronométrie",
            "Heritage GMT Automatic",
            "Heritage Spirit",
            "Heure H",
            "Highlife",
            "Highlife Automatic COSC",
            "Highlife COSC",
            "Highlife Chronograph Automatic",
            "Highlife Heartbeat Automatic",
            "Highlife Lady",
            "Historiques",
            "Horological Smartwatch",
            "Hydro",
            "Hydroconquest",
            "Hydronaut",
            "Imperiale",
            "Ingenieur",
            "Ingenious",
            "Intra-Matic",
            "Jazzmaster",
            "Jazzmaster Auto Chrono",
            "Jazzmaster Chrono Quartz",
            "Jazzmaster Day Date",
            "Jazzmaster Face-2-Face",
            "Jazzmaster Lady Quartz",
            "Jazzmaster Maestro",
            "Jazzmaster Open Heart",
            "Jazzmaster Performer Auto Chrono",
            "Jazzmaster Seaview",
            "Jazzmaster Thinline",
            "Jazzmaster Viewmatic",
            "Jules Audemars",
            "Jumbo",
            "Kelly",
            "Khaki",
            "Khaki Aviation",
            "Khaki Field",
            "Khaki GMT",
            "Khaki Navy",
            "Khaki Officer",
            "Khaki Pilot",
            "Khaki Pioneer",
            "King Power",
            "King Seiko",
            "Kirium",
            "L.U.C",
            "La Grande Classique",
            "Ladies Automatic Small Seconds",
            "LadyMatic Co-Axial",
            "Lange 1",
            "Laureato",
            "Legend Diver",
            "Liberty",
            "Linea",
            "Link",
            "Long Island",
            "Lucea",
            "Luminor",
            "Luminor 1950",
            "Luminor Base",
            "Luminor GMT",
            "Luminor Logo",
            "Luminor Marina",
            "Luminor Power Reserve",
            "Luminor Submersible",
            "Lunaris",
            "MDM",
            "Manta Ray",
            "Marine",
            "Marine Star",
            "Master",
            "Master Banker",
            "Master Collection",
            "Master Compressor",
            "Master Control",
            "Master Geographic",
            "Master Square",
            "Master Ultra Thin",
            "Meisterstück",
            "Memovox",
            "Milgauss",
            "Mille Miglia",
            "Monaco",
            "Monaco Calibre 6",
            "Monaco Calibre 11 Steve McQueen",
            "Monaco Calibre 12 Steve McQueen",
            "Monaco Calibre 17",
            "Monsoon",
            "Montbrillant",
            "MoonSwatch - Mission on Earth",
            "MoonSwatch - Mission to Jupiter",
            "MoonSwatch - Mission to Mars",
            "MoonSwatch - Mission to Mercury",
            "MoonSwatch - Mission to Neptune",
            "MoonSwatch - Mission to Pluto",
            "MoonSwatch - Mission to Saturn",
            "MoonSwatch - Mission to Uranus",
            "MoonSwatch - Mission to Venus",
            "MoonSwatch - Mission to the Moon",
            "MoonSwatch - Mission to the Sun",
            "Must de Cartier",
            "Must de Cartier 21",
            "Must de Cartier Colisée Vermeil",
            "Must de Cartier Vendome",
            "Médor",
            "NO01",
            "NO01 Steel",
            "NO02 Automatic",
            "Nantucket",
            "Nautilus",
            "Navitimer",
            "Navitimer Airborne",
            "Navitimer B01",
            "Navitimer GMT",
            "Navitimer Heritage",
            "Navitimer Montbrilliant 01 Limited",
            "Navitimer World",
            "Never Get Lost Carbonox",
            "Octo",
            "Old Navitimer",
            "Old Navitimer II",
            "Overseas",
            "Oyster Perpetual",
            "Oyster Perpetual Bubbleback",
            "Oyster Perpetual Date",
            "Oyster Perpetual Date Lady",
            "Oyster Perpetual Datejust",
            "Oyster Perpetual Lady",
            "Oyster Precision",
            "Oyster Speedking Precision",
            "Oysterdate Precision",
            "PRX",
            "PanoMatic",
            "Panthere",
            "Pasha",
            "Pasha Seatimer",
            "Patrimony",
            "Pelagos",
            "Pilot",
            "Polaris",
            "Polo",
            "Porsche Design",
            "Port Royal",
            "Portofino",
            "Portofino Chronograph",
            "Portugieser",
            "Premier",
            "Presage",
            "Presence",
            "PrimaLuna",
            "Prince Date",
            "Prince Oysterdate",
            "Princess",
            "Professional Diver 1000M \"Tsunami\"",
            "Promaster",
            "Promesse",
            "Prospex",
            "Proud Heritage Automatic Skeleton",
            "Radiomir",
            "Radiomir 3 Days",
            "Radiomir 10 days",
            "Radiomir 1940",
            "Radiomir Black Seal",
            "Raider Sea Bird",
            "Railmaster",
            "Record",
            "Recraft",
            "Reverso",
            "Reverso Classique",
            "Reverso Lady",
            "Riviera",
            "Roadster",
            "Ronde",
            "Ronde Croisière de Cartier",
            "Ronde Louis",
            "Ronde Must",
            "Ronde Solo",
            "Royal",
            "Royal Oak",
            "Runabout",
            "SKX",
            "Santos",
            "Santos 100",
            "Santos Dumont",
            "Santos Galbée",
            "Santos Octagon",
            "Santos Ronde",
            "Scuba Fifty Fathoms",
            "Sea-Dweller",
            "Sea-Dweller Deep Sea",
            "Sea-Hawk",
            "\"Seadiving\" 300M",
            "Seamaster",
            "Seamaster 30M",
            "Seamaster 120M",
            "Seamaster 300",
            "Seamaster 1948",
            "Seamaster Anakin Skywalker",
            "Seamaster Aqua Terra 150M",
            "Seamaster Chronograph",
            "Seamaster Cosmic",
            "Seamaster Day-Date",
            "Seamaster De Ville",
            "Seamaster Diver 200M",
            "Seamaster Diver 300M",
            "Seamaster F300Hz",
            "Seamaster Mariner",
            "Seamaster Memomatic Alarm",
            "Seamaster Olympic Games Collection",
            "Seamaster Planet Ocean 600M",
            "Seamaster Polaris",
            "Seamaster Professional 200M",
            "Seamaster Proplof 1200M",
            "Seamaster Railmaster",
            "Seamaster Sensor Quartz",
            "Seastar",
            "Seastar 1000",
            "Seastar 1000 Chronograph",
            "Seiko 5",
            "Seiko 5 Automatic Day-Date",
            "Senator",
            "Silverstone",
            "Sky-Dweller",
            "Slimline",
            "Slimline Moonphase",
            "Solotempo",
            "Speedmaster",
            "Speedmaster 57",
            "Speedmaster Broad Arrow",
            "Speedmaster Co-Axial",
            "Speedmaster Date",
            "Speedmaster Day-Date",
            "Speedmaster De Luxe",
            "Speedmaster Legend",
            "Speedmaster Mark II",
            "Speedmaster Mark IV",
            "Speedmaster Mark V",
            "Speedmaster Michael Schumacher",
            "Speedmaster Moon Phase",
            "Speedmaster Professional Moonwatch",
            "Speedmaster Racing",
            "Speedmaster Reduced",
            "Speedmaster Spacemaster",
            "Speedmaster Split-Seconds",
            "Speedmaster Triple Date",
            "Speedmaster X-33",
            "Spezimatic",
            "Spirit of Liberty",
            "Sporto",
            "Spyder",
            "Star",
            "Startimer Pilot Chronograph",
            "Stellina",
            "Submariner",
            "Submariner Date",
            "Submariner Hulk",
            "Submariner No Date",
            "Submerged 30 ATM",
            "Summit",
            "SuperOcean Chronograph",
            "SuperOcean Heritage II",
            "SuperOcean II",
            "SuperOcean Professional",
            "Superocean",
            "Superocean Heritage",
            "Supersport Chronograph",
            "Swordfish",
            "TT1",
            "TT3",
            "Tandem",
            "Tank",
            "Tank Américaine",
            "Tank Anglaise",
            "Tank Française",
            "Tank Louis",
            "Tank MC",
            "Tank Must de Cartier",
            "Tank Solo",
            "Timewalker",
            "Torpedine",
            "Tradition",
            "Transocean",
            "Twenty 4",
            "Type XX",
            "Ultra-Chron",
            "Unknown",
            "Urban Mystique Chronograph",
            "V-Extreme Pro Chronograph",
            "Vanguard",
            "Villeret",
            "Vintage",
            "Vintage 1945",
            "Vintage Rally",
            "Williams F1 Team",
            "Windrider",
            "Yacht-Master",
            "Yacht Timer"
        ];
    }

    public static function d_period(): array
    {
        return [
            "1850-1900",
            "1900-1949",
            "1950-1959",
            "1960-1969",
            "1970-1979",
            "1980-1989",
            "1990-1999",
            "2000-2010",
            "2010-2020",
            "2020+",
            "Earlier than 1850"
        ];
    }

    public static function d_movement(): array
    {
        return [
            "Automatic",
            "Manual winding",
            "Other",
            "Quartz"
        ];
    }

    public static function d_case_material(): array
    {
        return [
            "Aluminium",
            "Argentan",
            "Bioceramic",
            "Bronze",
            "Carbon",
            "Ceramic",
            "Chromed",
            "Copper",
            "Gold",
            "Gold/Steel",
            "Gold-filled",
            "Gold-plated",
            "Gunmetal",
            "Metal",
            "Palladium",
            "Pink gold",
            "Plastic",
            "Platinum",
            "Polycarbon",
            "Silver",
            "Silverplated",
            "Stainless steel",
            "Steel",
            "Tantalum",
            "Titanium",
            "Tungsten",
            "White gold",
            "Yellow gold"
        ];
    }

    public static function d_case_diameter(): array
    {
        return [
            'Less than 20 mm',
            '20 mm',
            '21 mm',
            '22 mm',
            '23 mm',
            '24 mm',
            '25 mm',
            '26 mm',
            '27 mm',
            '28 mm',
            '29 mm',
            '30 mm',
            '31 mm',
            '32 mm',
            '33 mm',
            '34 mm',
            '35 mm',
            '36 mm',
            '37 mm',
            '38 mm',
            '39 mm',
            '40 mm',
            '41 mm',
            '42 mm',
            '43 mm',
            '44 mm',
            '45 mm',
            '46 mm',
            '47 mm',
            '48 mm',
            '49 mm',
            '50 mm',
            'Greater than 50 mm'
        ];
    }

    public static function d_condition(): array
    {
        return [
            "Fair - major signs of wear",
            "Good - visible signs of wear",
            "New",
            "Unworn - no signs of wear",
            "Very good - minor signs of wear"

        ];
    }

    public static function d_gender(): array
    {
        return [
            'Men',
            'Unisex',
            'Women'
        ];
    }

    public static function d_band_material(): array
    {
        return [
            "Bronze",
            "Ceramic",
            "Gold/steel",
            "Leather",
            "Platinum",
            "Resin",
            "Rose gold",
            "Rubber",
            "Steel",
            "Textile",
            "Titanium",
            "White gold",
            "Yellow gold"
        ];
    }

    public static function d_band_length(): array
    {
        return [
            "Very short (under 160 mm)",
            "Short (160-170 mm)",
            "Regular (180-200 mm)",
            "Long (over 200 mm)"
        ];
    }

    public static function d_dial_colour(): array
    {
        return [
            "Black",
            "Blue",
            "Bronze",
            "Brown",
            "Champagne",
            "Gold",
            "Green",
            "Grey",
            "Mother of pearl",
            "Navy",
            "Orange",
            "Pink",
            "Purple",
            "Red",
            "Salmon",
            "Silver",
            "Skeleton",
            "Turquoise",
            "White",
            "Yellow"
        ];
    }

    public static function d_weight(): array
    {
        return [
            "x_g",
            "x_kg",
            "x_t",
            "x_oz",
            "x_lb",
            "x_st"
        ];
    }

    public static function d_width_lug_watch_band(): array
    {
        return [
            "x_in",
            "x_ft",
            "x_yd",
            "x_mi",
            "x_mm",
            "x_cm",
            "x_m"
        ];
    }
}
