/* eslint-disable @typescript-eslint/no-explicit-any */
// Auto-generated by generate:ts-models

export interface Batch {
  created_at: string | null;
  created_by: number;
  default_destination: string;
  id: number;
  location_id: number;
  name: string;
  status_id: number;
  updated_at: string | null;
  createdBy?: User;
  location?: Location;
  status?: Status;
  watches?: Watch[];
}

export interface Brand {
  code: string;
  created_at: string | null;
  id: number;
  name: string;
  updated_at: string | null;
  watches?: Watch[];
  wishlists?: Wishlist[];
}

export interface Cache {
  expiration: number;
  key: string;
  value: string;
}

export interface CacheLock {
  expiration: number;
  key: string;
  owner: string;
}

export interface FailedJob {
  connection: string;
  exception: string;
  failed_at: string;
  id: number;
  payload: string;
  queue: string;
  uuid: string;
}

export interface JobBatch {
  cancelled_at: number | null;
  created_at: number;
  failed_job_ids: string;
  failed_jobs: number;
  finished_at: number | null;
  id: string;
  name: string;
  options: string | null;
  pending_jobs: number;
  total_jobs: number;
}

export interface Job {
  attempts: number;
  available_at: number;
  created_at: number;
  id: number;
  payload: string;
  queue: string;
  reserved_at: number | null;
}

export interface Location {
  country: string | null;
  created_at: string | null;
  id: number;
  name: string;
  updated_at: string | null;
  batches?: Batch[];
  watches?: Watch[];
}

export interface Log {
  created_at: string | null;
  id: number;
  message: string;
  type: string;
  updated_at: string | null;
  user_id: number | null;
  user?: User;
}

export interface Migration {
  batch: number;
  id: number;
  migration: string;
}

export interface ModelHasPermission {
  model_id: number;
  model_type: string;
  permission_id: number;
  permission?: Permission;
}

export interface ModelHasRole {
  model_id: number;
  model_type: string;
  role_id: number;
  role?: Role;
}

export interface Notification {
  created_at: string | null;
  data: string;
  id: string;
  notifiable_id: number;
  notifiable_type: string;
  read_at: string | null;
  type: string;
  updated_at: string | null;
}

export interface PasswordResetToken {
  created_at: string | null;
  email: string;
  token: string;
}

export interface Permission {
  created_at: string | null;
  guard_name: string;
  id: number;
  name: string;
  updated_at: string | null;
  modelHasPermissions?: ModelHasPermission[];
  roleHasPermissions?: RoleHasPermission[];
}

export interface PlatformDatum {
  created_at: string | null;
  data: any | null;
  id: number;
  platform: any;
  status: string;
  updated_at: string | null;
  watch_id: number;
  watch?: Watch;
}

export interface RoleHasPermission {
  permission_id: number;
  role_id: number;
  permission?: Permission;
  role?: Role;
}

export interface Role {
  created_at: string | null;
  guard_name: string;
  id: number;
  name: string;
  updated_at: string | null;
  modelHasRoles?: ModelHasRole[];
  roleHasPermissions?: RoleHasPermission[];
}

export interface Session {
  id: string;
  ip_address: string | null;
  last_activity: number;
  payload: string;
  user_agent: string | null;
  user_id: number | null;
}

export interface Setting {
  created_at: string | null;
  group: string | null;
  id: number;
  is_public: number;
  key: string;
  type: string;
  updated_at: string | null;
  value: string | null;
}

export interface Stage {
  created_at: string | null;
  id: number;
  name: string;
  updated_at: string | null;
  watches?: Watch[];
}

export interface Status {
  created_at: string | null;
  id: number;
  name: string;
  updated_at: string | null;
  batches?: Batch[];
  watches?: Watch[];
}

export interface Transaction {
  amount: number;
  created_at: string | null;
  currency: string;
  id: number;
  payment_type: any;
  status: any;
  type: any;
  updated_at: string | null;
  user_id: number;
  watch_id: number | null;
  user?: User;
  watch?: Watch;
}

export interface User {
  country: string;
  created_at: string | null;
  currency: string;
  email: string;
  email_verified_at: string | null;
  id: number;
  last_login_at: string | null;
  last_login_ip: string | null;
  name: string;
  password: string;
  remember_token: string | null;
  status: string;
  updated_at: string | null;
  batches?: Batch[];
  logs?: Log[];
  transactions?: Transaction[];
  watches?: Watch[];
  wishlists?: Wishlist[];
}

export interface WatchImage {
  created_at: string | null;
  filename: string | null;
  id: number;
  order_index: number;
  public_url: string | null;
  thumbnail: string | null;
  updated_at: string | null;
  use_for_ai: number;
  watch_id: number;
  watch?: Watch;
}

export interface WatchLog {
  action: string;
  created_at: string | null;
  details: string | null;
  id: number;
  updated_at: string | null;
  watch_id: number;
  watch?: Watch;
}

export interface Watch {
  agent_id: number | null;
  ai_instructions: string | null;
  batch_id: number | null;
  brand_id: number;
  caliber: string | null;
  case_size: string | null;
  created_at: string | null;
  current_cost: number | null;
  description: string | null;
  description_thread_id: string | null;
  id: number;
  location_id: number | null;
  name: string;
  notes: string | null;
  original_cost: number | null;
  reference: string | null;
  seller_id: number | null;
  serial_number: string | null;
  sku: string;
  stage_id: number;
  status_id: number;
  timegrapher: string | null;
  updated_at: string | null;
  user_id: number;
  agent?: User;
  batch?: Batch;
  brand?: Brand;
  location?: Location;
  seller?: User;
  stage?: Stage;
  status?: Status;
  user?: User;
  platformDatas?: PlatformDatum[];
  transactions?: Transaction[];
  watchImages?: WatchImage[];
  watchLogs?: WatchLog[];
}

export interface Wishlist {
  brand_id: number | null;
  created_at: string | null;
  currency: string;
  id: number;
  image_url: string | null;
  name: string;
  price_range_max: number | null;
  price_range_min: number | null;
  updated_at: string | null;
  user_id: number;
  brand?: Brand;
  user?: User;
}

