import {
    BadgeEuro,
    Calendar,
    ChartArea,
    ChartNoAxesColumnIncreasing,
    Clock,
    Database,
    File,
    Gauge,
    Hammer,
    LayoutList,
    List,
    Network,
    PackageOpen,
    Settings,
    Store,
    Users,
    Watch,
} from "lucide-react";

export const menus = [
    { name: "Dashboard", permission: "dashboard", icon: ChartArea, path: "/" },
    {
        name: "Watch Management",
        permission: "watchManagement",
        icon: Clock,
        path: "/watches",
    },
    {
        name: "Multi-platform Sales",
        permission: "multiplatformSales",
        icon: ChartNoAxesColumnIncreasing,
        path: "/sales",
    },
    {
        name: "Batch Management",
        permission: "batchManagement",
        icon: PackageOpen,
        path: "/batch",
    },
    {
        name: "Promote / Social Media",
        permission: "promote",
        icon: Calendar,
        path: "/promote",
        opacity: "opacity-50",
    },
    {
        name: "Sales History / Stats",
        permission: "salesHistory",
        icon: BadgeEuro,
        path: "/history",
    },
    {
        name: "Performance Tracking",
        permission: "performanceTracking",
        icon: Gauge,
        path: "/performance",
        opacity: "opacity-50",
    },
    {
        name: "Wish List",
        permission: "wishList",
        icon: LayoutList,
        path: "/wishlist",
    },
    {
        name: "Agent Balance",
        permission: "agentsBalance",
        icon: Network,
        path: "/payments",
    },
    {
        name: "Agent Watches",
        permission: "watchManagement",
        icon: Watch,
        path: "/agent-watches",
    },
    {
        name: "Seller Watches",
        permission: "watchManagement",
        icon: Store,
        path: "/sellers",
    },
    {
        name: "Invoices",
        permission: "invoices",
        icon: File,
        path: "/invoices",
        opacity: "opacity-50",
    },
    { name: "Users", permission: "users", icon: Users, path: "/users" },
    {
        name: "Tools",
        permission: "tools",
        icon: Hammer,
        path: "/tools",
        opacity: "opacity-50",
    },
    {
        name: "Full Data View",
        permission: "fullDataView",
        icon: Database,
        path: "/data",
    },
    {
        name: "Settings",
        permission: "settings",
        icon: Settings,
        path: "/settings",
    },
    { name: "Log", permission: "log", icon: List, path: "/log" },
];
